export const collegeText = {
  college: "College",
  addcollege: "Create College",
  editcollege: "Edit College",
  collegename: "college Name",
  address: "Address",
  phonenumber: "Phone Number",
  email: "Email",
  contractdoc: "Contract Doc",
  subscription: "Subscription Type",
  studentlimit: "Student Limit",
  upload: "Upload",
  createcollege: "Create College",
  updatecollege: "Update College",
  uploadlogo: "Upload Logo",
  numberofstudent: "No.of Student",
  status: "Status",
  action: "action",
  Action: "Action",
  active: "active",
  inactive: "inactive",
  alltype: "All Type",
  deleted: "Deleted",
  sizelimit: "Size limit 5mb",
  required: "Required",
  delete: "deleted",
  update: "update",
  ok: "ok",
  b2b: "B to B",
  b2c: "B to C",
  alllist: "All List",
};
