export const registerText = {
  errormsg: "Required",
  errorclg: "Enter valid College",
  errordepartment: "Enter valid Department",
  cardFirstTitle: "Sign Up",
  cardSecondTitle: "Department",
  cardThirdTitle: "Email",
  name: "Name",
  mobile: "Mobile",
  country: "Country",
  profilepicture: "Profile Picture",
  nextbutton: "Next",
  oauthtitle: "or SignUp With",
  email: "Email",
  college: "College",
  department: "Department",
  batch: "Graduation",
  email: "Email",
  password: "Password",
  newpassword: "New Password",
  confirmpassword: "Confirm Password",
  submit: "Send OTP",
  submittext: "Submit",
  alertmsg: "Link has been sent to your Registered",
  emailid: "email-id",
  // new texts
  Wevesent: "We’ve sent a verification OTP code to your",
  Emailid: "Email id",
  OK: "OK",
  ResendOTP: " Resend OTP",
  OTPhasbeen: " OTP has been",
  Resend: "Resend",
  toyour: "to your",
  emailid: "email id",
  VerifyOTPCreateAccount: " Verify OTP & Create Account",
  Signup: "Sign up",
  Required: "Required",
  country: "country",
  ProfilePicture: " Profile Picture",
  Next: "Next",
  orsignupwith: "or signup with",
  College: "College *",
  Department: "Department *",
  Graduation: "Graduation",
  SendOTP: " Send OTP",
};
