export const expertText = {
  mentorlist: "Expert List",
  name: "Name",
  industryname: "Industry Name",
  emailid: "Email ID",
  worklog: "Worklog",
  phonenumber: "Phone Number",
  email: "Email",
  industry: "Industry",
  mobile: "Mobile",
  company: "Company",
  uploadprofile: "Upload Profile",
  position: "Position",
  creatementor: "Create Expert",
  editmentor: "Edit Expert",
  numberofstudent: "No.of Student",
  status: "Status",
  action: "action",
  Action: "Action",
  active: "active",
  inactive: "inactive",
  alltype: "All Type",
  deleted: "Deleted",
  sizelimit: "Size limit 5mb",
  required: "Required",
  delete: "deleted",
  EditExpert: "Edit Expert",
  CreateExpert: "Create Expert",
};
