export const studentText = {
  studentlist: "Student List",
  name: "Name",
  industryname: "Industry Name",
  emailid: "Email ID",
  worklog: "Worklog",
  phonenumber: "Phone Number",
  email: "Email",
  industry: "Industry",
  mobile: "Mobile",
  company: "Company",
  uploadprofile: "Upload Profile",
  position: "Position",
  creatementor: "Create Mentor",
  editmentor: "Edit Mentor",
  numberofstudent: "No.of Student",
  status: "Status",
  action: "action",
  Action: "Action",
  active: "active",
  inactive: "inactive",
  alltype: "All Type",
  deleted: "Deleted",
  sizelimit: "Size limit 5mb",
  required: "Required",
  stages: "stages",
  stage1: "stage1",
  stage2: "stage2",
  stage3: "stage3",
  college: "College",
  progress: "Progress",
  approve: "student Approval",
  approved: "approve",
};
