export const mentorText = {
  modaltitle: " Create Webinar",
  editModal: "Edit Modal",
  title: " Title",
  description: "Description",
  date: " Date",
  time: " Time",
  create: " Create",
  required: "Required",
  update: "Update",
  timeout: "Time Out",
  // NEW UPDATES
  Appointments: "Appointments",
  join: "join",
  Appointmentschedule: "Appointment schedule",
  to: "to",
  Stage1: " Stage 1",
  NoappointmentScheduled: "No appointment Scheduled",
  Webinar: "Webinar",
  // join: "join",
  Viewmore: "View more",
  NoWebinorScheduled: "No Webinor Scheduled",
  Whydoyouwant: "Why do you want to Delete the Webinar.?",
  // Confirm: "Confirm",
  Title: "Title",
  Descritption: "Descritption",
  WebinarDetails: "Webinar Details",
  DateandTime: "Date and Time",
  Presenter: "Presenter",
  Feeds: "Feeds",
  Activity: "Activity",
  Feed: "Feed",
  Community: "Community",
  // NoWebinorScheduled: "No Webinor Scheduled",
  WhydoyouwanttoDeletetheWebinar: "Why do you want to Delete the Webinar.? ",
  Confirm: "Confirm",
  Ok: "Ok",
};
