export const homeText = {
  communtiy: "Communtiy",
  Feeds: "Feeds",
  Activity: "Activity",
  Local: "Local",
  Global: "Global",
  Appointment: "Appointment",
  Mentor: "Mentor",
  join: "join",
  Create: "Create",
  Reschedule: "Re-schedule",
  IndustryExpert: "Industry Expert",
  Webinar: "Webinar",
  Viewmore: "View more",
  NoWebinorScheduled: "No Webinor Scheduled",
  FeedbackQuestion: "Feedback Question",
  Loremipsum:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam, purus sit amet luctus venenatis",
  Yes: "Yes",
  No: "No",
  WebinarDetails: "Webinar Details",
  DateandTime: "Date and Time",
  Presenter: "Presenter",
  Doyouwant: "Do you want to cancel the appointment",
  Confirm: "Confirm",
  DoyouwanttoReSchedule: "Do you want to ReSchedule the appointment",
  ok: "Ok",
  // student home page texts
  Progress: "Progress",
  Stage: "Stage",
  Studentanalytics: "Student analytics",
  Completed: "Completed",
  Resume: "Resume",
  // WebinarTitle: " Webinar Title",
  NaveenRajendran: "Naveen Rajendran",
  NUmber: "2",
  VisualDesigner: "Visual Designer",
  WebinarTitle: "Webinar Title",
  Loremipsumdolorsitamet: "Lorem ipsum dolor sit amet",
  DataJuly: " 18 July 2021",
  Am: "9 AM",
  Time: "3.00 pm",
  username: "user name",
  // student appoitment texts
  Youhavemissed: "You have missed an appointment with expert!",
  Reschedules: "Reschedule",
  Createanappointment: "Create  an appointment with the Expert or Mentor",
};
