export const studentProfileText = {
  batch: "Batch",
  mentor: "Mentor",
  expert: "Industry Expert",
  industrycmmnt: "Industry Comments",
  report: "Report",
  topic: "Topic",
  stage: "stage",
  hours: "Hours",
  topicslearned: "Topics learned",
  content: "Student haven’t finished stage level 3",
  appointment: "Appointment",
  required: "Required",
  notfound: "Content Not Found",
  cancel: "Cancel",
  waitingapproval: "Waiting For Approval",
  approve: "Approve",
};
