export const college_text = {
  Dotts: "●●●●●●●●",
  SubscriptionPlan: "Subscription Plan",
  SubscriptionType: "Subscription Type",
  Premium: "Premium",
  StudentLimits: "Student Limits",
  Numbers: "200",
  Date: "Date",
  Dates: "10.20.2012",
  Department: "Department",
  Student: "Student",
  SupportContact: "Support Contact",
  email_id: "College@gmail.com",
  phoneno: "9710452661",
  Industry: "Industry",
  Viewmore: "View more",
  EditEmail: "Edit Email",
  Email: "Email",
  Editpassword: "Edit password",
  password: "password",
  Edit: "Edit",
  ok: "ok",
};
