export const studentProfileUser_Text = {
  Details: "Details",
  Industry: "Company",
  Domain: "Position",
  Personal_Details: "Personal Details",
  Phone: "Phone",
  Password: "Password",
  Students: "Students",
  View_more: "View more",
  Student_Appointment_List: "Student Appointment List",
  Completed_Students: "Completed Students",
  // new mentor_profile_layout text
  Loading: " Loading...",
  Stage: "Stage",
  Dotts: "●●●●●●●●",
  // Student Appoinment tetxs
  Nodatafound: "No data found",
  Graphdatanotfound: "Graph data not found",
  Appointment: "Appointment",
  Am9: " 9 AM",
  Am10: "10 AM",
  Join: "Join",
  nofeedsfound: "no feeds found",
  TopicsLearned: "Topics Learned",
  Notopicsfound: "No topics found",
  Analytics: "Analytics",
  IndustryExpertFeedback: "Industry Expert Feedback",
  edit: "edit",
};
