export const AppoinmentText = {
  Appointment: "Appointment",
  Mentor: "Mentor",
  IndustryExpert: "Industry Expert",
  join: "join",
  SingleDate: "Single Date",
  RangeDate: "Range Date",
  AvailbaleSlots: "Availbale Slots",
  Sorry: "Sorry",
  PleaseSelectDate: "Please Select Some Other Date",
  SlotsisnotAvailable: "Slots is not Available",
  BookNow: "Book Now",
  Confirm: "Confirm",
  ok: "ok",
  Doyouappointment: "Do you want to Cancel the appointment",
  timeout: "Completed",
  // calender texts
  SelectDate: "Select Date",
  Mon: "Mon",
  Tue: "Tue",
  Wed: "Wed",
  Thur: "Thur",
  Fri: "Fri",
  Sat: "Sat",
  Sun: "Sun",
};
