export const cmsText = {
  cmstitle: "Content Management System",
  homepage: "Home Page",
  industry: "Industry",
  configurereport: "Configure Report",
  course: "Course",
  bloglist: "Blog List",
  create: "Create",
  image: "Image",
  title: "Title",
  description: "Description",
  save: "save",
  add: "Add",
  edit: "edit",
  termsandcondition: "Terms & Conditions",
  privacypolicy: "Privacy Policy",
  createblog: "Create Blog",
  editblog: "Edit Blog",
  bodycontent: "Body Content",
  content: "Click To Upload",
  imagesize: "Accept file : jpg,png,img up to 20MB",
  question: "Question",
  action: "Action",
  topiclearnt: "Topic Learnt",
  addquestion: "Add Question",
  editquestion: "Edit Question",
  topiclearnt: "Topic Learnt",
  addtopiclearnt: "Add Topic Learnt",
  edittopiclearnt: "Edit Topic Learnt",
  name: "Name",
  numberofstudent: "No. of Student",
  video: "Video",
  status: "Status",
  industrylist: "Industry List",
  action: "Action",
  CreateIndustry: "Create Industry",
  industryname: "Industry Name",
  industrydescription: "Industry description",
  uploadlogo: "Upload logo",
  sizelimitcourse: "Size limit 500MB",
  editindustry: "Edit Industry",
  industryname: "Industry Name",
  industrydescription: "Action",
  uploadlogo: "Upload logo",
  sizelimit: "Size limit 500KB",
  sizelimitidustry: "Size limit 20MB",
  stage: "stage",
  text: "image",
  video: "Video",
  contentduration: "Content Duration",
  upload: "Upload",
  htmlfile: "HTML file",
  numberofcount: "No.ofcount",
  editcourse: "Edit Course Content",
  required: "Required",
  createcourse: "Create Course",
};
